### ISSUE TITLE
openSUSE_Leap_42.1.txt

### ISSUE THREAD

**Issue by CHMBroeders** [junzis/aircraft-id-finder#2]
[openSUSE_Leap_42.1.txt](https://github.com/junzis/aircraft-db/files/409830/openSUSE_Leap_42.1.txt)
I hope you can read this text. I propose to put it in your git-repo
Best greetings,
C. Broeders

**Comment by junzis** [comment]
Thanks for the guide. however it is rather platform specific. I have updated the README for a more general purpose. https://github.com/junzis/aircraft-db/commit/bcc76e31e081262edbf203ce36bfaa54db161de6
