### ISSUE TITLE
export aircraft_db.csv file without dos characters

### ISSUE THREAD

**Issue by CHMBroeders** [junzis/aircraft-id-finder#3]
[export_m_py.txt](https://github.com/junzis/aircraft-db/files/414114/export_m_py.txt)
The attached file to replace export.py creates smaller csv files without dos-characters, as to be used on LINUX systems. Otherwise, on LINUX dos2unix should be applied for follow-up processing of csv file.

**Comment by junzis** [comment]
@CHMBroeders , Python default using '\r\n' as line terminator. I am using it Linux all the times, which does not seems to be a problem. would you please paste error code here?

**Comment by CHMBroeders** [comment]
0D0011,XA-HMM,AS65,NONE,NONE^M
last line just downloaded your aircraft_db.csv file with ^M ending.
Creation of this file with my LINUX computer shows [dos] on last line:
"aircraft_db.csv" [dos] 9083L, 329244C

**Comment by junzis** [comment]
ok, I see now. I will fix this.

**Comment by eroom1966** [comment]
Hi Junzis
Great project!
is your online database still working, it looks as though it is no longer responding to requests
Regards

**Comment by junzis** [comment]
@leemoore1966 : thanks for letting me know,  it is up running again now.

**Comment by eroom1966** [comment]
Hi Junzis,
Thanks for the fix.
It appears that the option to "Export All Data .csv", now gives
"Page Not Found"
Thx
Lee

**Comment by junzis** [comment]
@leemoore1966  this is also fixed now. thanks!
