### ISSUE TITLE
Database out of date

### ISSUE THREAD

**Issue by eroom1966** [junzis/aircraft-id-finder#6]
Hi Junzis

the database hosted here https://junzisun.com/adb/ seems to be out of date
I tried to query the ID 4072DC, this is found in the search 'Quick search by aircraft ICAO address ', but the 'download database' is missing this ID

is it possible to refresh the Database listing ?

**Comment by junzis** [comment]
Thanks @eroom1966, it is fixed now, with new commits 308645c711846b963de74d02a41719e7a5eb9853 and 7e055a2820366db3fb0f40311215416251204c13.

**Comment by eroom1966** [comment]
Great Thanks!
E
