### ISSUE TITLE
Database out of date

### ISSUE THREAD

**Issue by eroom1966** [junzis/aircraft-id-finder#7]
Hi Junzi

Seems that the database may be out of date again
ICAO code 406313, should be mapped to G-SHMN
This is shown on ginfo and FR24
the database is showing the old registration of G-GKEV

Thx
Lee

**Comment by junzis** [comment]
The terms of FR24 has changed. So it is not possible to use it as the source of our data. 

An alternative aircraf database is:

https://opensky-network.org/aircraft-database

**Comment by eroom1966** [comment]
Many thanks for the pointer
